CC = gcc
CFLAGS =-L../raylib/lib -L../bin -lrect-collision -lraylib -lglfw -lGL -lm -lpthread -ldl -lrt -lX11 -Wall -Wextra -Werror -pedantic

all:
	$(CC) -o ray-collision-example ray-collision-example.c $(CFLAGS)
